// Pure-Lua KHR_interactivity runtime, exported as source text (see
// lua-sources.ts, generated by scripts/build-lua-sources.mjs from src/lua/
// *.lua) for a host to load into a Lua VM (this repo uses wasmoon — see
// packages/conformance/src/run-compiled-lua.ts).
export * from "./lua-sources.js";
